services:
  kobra-unleashed:
    ports:
      - "5000:5000"
    volumes:
      - ./certs:/app/certs
      - ./uploads:/app/uploads
    restart: always
    image: kobra-unleashed
    build:
      context: .
    environment:
      - MQTT_HOST=eclipse-mosquitto
      - MQTT_PORT=8883
      #- ROOT_URL=http://rpi_static_ip:5000
      - ROOT_URL=http://192.168.1.234:5000
    container_name: kobra-unleashed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      eclipse-mosquitto:
        condition: service_started
  eclipse-mosquitto:
    stdin_open: true
    tty: true
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs/:/certs/
    image: eclipse-mosquitto
